services:
  pipeline:
    build: .
    container_name: carbon_pipeline_container
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
    volumes:
      - .:/app